### ISSUE TITLE
Portfolio: application deploy

### ISSUE THREAD

**Issue by pulgosodog** [pulgosodog/Portfolio-template-1#6]
Online version of the app:
## https://pulgosodog.github.io/Portfolio-template-1/

**Comment by V-Blaze** [comment]
## Hi @pulgosodog , 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![almost-there](https://user-images.githubusercontent.com/107632780/229242540-644ade4a-fe15-4f4c-a38b-6ded70cc4e8b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Deployed project works fine✔
- Portfolio deployed using GitHub pages👋 ✔

 ## Required Changes ♻️
- [ ] You did great deploying your portfolio correctly, :+1: :+1:  But as stated in the project requirement, you need to update the `live demo` section of your readme with the link to the deployed project, I can see you currently have a link to this issue there, I'll suggest you edit that and add the link to the live project there, :smile: :wave: 
> Update the README of your repository to include a link to the online version. 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by pulgosodog** [comment]
Hello! My bad, I've fixed it, I appreciate the help. 🙌

**Comment by taldr27** [comment]
# Status: Approved! 🟢 
Hi @pulgosodog, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3oEjI5VtIhHvK37WYo/giphy.gif)

## Highlights 🎉 
✅ Professional and customized README. 🙌
✅ README includes a working live link. 🎯
✅ Successfully deployed using GitHub Pages. 🤓
✅ Live page is fully functional. 👍

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_
